### ISSUE TITLE
Get blue text on bootloader/ fastboot saying : Please Check "Enable OEM Unlock"  In your Developer Options

### ISSUE THREAD

**Issue by aesth-real** [steadfasterX/SALT#42]
Device: LMG710-EAW ( LG G7 THINQ ) 
Software: A13 , unlocked bootloader

All the functions of fastboot and bootloader work fine , just get this blue text..

I booted into download mode
Read the partitions
Rebooted normally
Now I get this blue text in my bootloader

**Comment by aesth-real** [comment]
![IMG-20230902-WA0000](https://github.com/steadfasterX/SALT/assets/69789584/cb6d23bd-9998-47ae-981b-b63830f19e8c)

**Comment by steadfasterX** [comment]
I am not even sure if that is an error or not! It does NOT look like one. this is just a info and as long as you do not modify the fastboot sources (which you can't) you have to live with that . regardless of that and as posted in the SALT thread this is nothing SALT caused (other then you triggered an internal mechanism by just using the download mode - or ofc if you have used wipe or flash) nor can be fixed by SALT, sorry
